### ISSUE TITLE
Update README with instructions and explanation

### ISSUE THREAD

**Issue by alphaX86** [pranalishinde28/BlockChain-Test#1]
### Description:
Hello there 👋 I saw your GitHub repo and realized that the README is quite vague and not understandable to beginners. So, a refactor may be needed for this one! :)

**Comment by alphaX86** [comment]
@pranalishinde28 review this issue and ping me back! ;)

**Comment by TusharDasMe** [comment]
i would like to take this issue .

**Comment by alphaX86** [comment]
Wait a sec @TusharDasMe I just opened an issue for the owner's repo. 😅 I still didn't get approval from @pranalishinde28 So let's wait or if no reply is received, the issue will be closed. So yeah

**Comment by pranalishinde28** [comment]
Yep I made the changes. You may go ahead now 😃

**Comment by pranalishinde28** [comment]
Sorry I didn't see your message. I ll revert back to you as soon as
possible. 👍🏻

**Comment by alphaX86** [comment]
Cool! 👍

**Comment by rsrkpatwari1234** [comment]
Hello!I would like to work upon this.

**Comment by pranalishinde28** [comment]
Sure! Go ahead and fork the repo. Feel free to make changes 😀
